# Generated by Django 5.0.2 on 2024-05-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertotal',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='ordertotal',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_item',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Ordertotal',
        ),
    ]
