# Generated by Django 5.0.2 on 2024-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_ordertotal_menu_remove_ordertotal_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pizza_quantity', models.IntegerField(default=0)),
                ('burger_quantity', models.IntegerField(default=0)),
                ('pasta_quantity', models.IntegerField(default=0)),
                ('fries_quantity', models.IntegerField(default=0)),
                ('cold_drinks_quantity', models.IntegerField(default=0)),
                ('sandwich_quantity', models.IntegerField(default=0)),
                ('dessert_quantity', models.IntegerField(default=0)),
                ('dessert_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_location', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
