# Generated by Django 5.0.2 on 2024-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_foodorder_delete_location_delete_login_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='delivery_location',
            field=models.CharField(max_length=200),
        ),
    ]
